services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopping
      POSTGRES_USER: shopping
      POSTGRES_PASSWORD: shopping
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
