spring.application.name=spring-shopping

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shopping
spring.datasource.username=shopping
spring.datasource.password=shopping
spring.jpa.hibernate.ddl-auto=validate

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/shopping

# Flyway
spring.flyway.enabled=true
